In [1]:
from dbManager import dbManager

db = dbManager()
locData = db.get_loc_data_by_day("mon")

TEMPORARY NOTEBOOK TO TEST STUFF

In [2]:
import pandas as pd

df = pd.DataFrame.from_records(locData['data'], columns=locData['cols'])
df.head()

,loc_id,rating,loc_name,tag_list,lat,long,est_loc_price,province,open_day,open_time,close_time
0,1,None,Samyan Mitrtown,"Historical Place, Mall, Shopping, Must See Att...",13.734461,100.528293,None,Bangkok,MON,00:00,24:00
1,4,None,Queen Saovabha Memorial Institute,"Historical Place, Must See Attraction, Local C...",13.732377,100.532679,None,Bangkok,MON,08:30,16:00
2,7,None,CentralWorld,"Shopping, Must See Attraction, Modern, Luxury,...",13.746577,100.539041,None,Bangkok,MON,10:00,22:00
3,8,None,Lumphini Park,"Park, Must See Attraction, Outdoor, Nature, Mo...",13.730729,100.541509,None,Bangkok,MON,04:30,22:00
4,9,None,Siam Paragon,"Shopping, Must See Attraction, Local Culture, ...",13.746778,100.534954,None,Bangkok,MON,10:00,22:00

In [3]:
inputs = {
    'must_add' : ('A', 'B', 'C'),
    'start_date' : '1/10/2020',
    'end_date' : '3/10/2020',
    # 'trip_type' : '3',
    # 'budget' : '1000', 
    # 'distance' : 'mid',
    'selected_tags' : ('Must See Attraction', 'Local Culture', 'Local Cuisine', 'Park', 'Religion'),
    'undesirable_tags' : ('Shopping',)
}

# want place like this
# {
#     'name' : '1', -> loc_id
#     'coordinate' : (0.53,-123),
#     'tags' : ['temple'],
#     'type' : ['food'],
#     'hours' : (0, 23),
#     'duration' : 60,
#     'durationH' : 1,
#     'rating' : randInt(5)
# }

In [21]:
df = pd.DataFrame.from_records(locData['data'], columns=locData['cols'])
df['tags'] = df['tag_list'].str.split(', ')
df['coordinate'] = list(zip(df['lat'],df['long']))
df['hours'] = list(zip(df.open_time,df.close_time))
df['type'] = ["tourist spot"] * len(df)
df['duration'] = 60 #temp
df['durationH'] = df.duration/60 #temp
df.drop(['est_loc_price',"loc_name","lat","long","province","open_day","open_time","close_time","tag_list"],axis=1,inplace=True)
df.rename(columns={'loc_id':'name'},inplace=True)
df = df[['name','coordinate','tags','type','hours','duration','durationH','rating']]
places = df.to_dict('records')

[{'name': 1,
  'coordinate': (13.7344606, 100.52829290867629),
  'tags': ['Historical Place',
   'Mall',
   'Shopping',
   'Must See Attraction',
   'Local Culture'],
  'type': 'tourist spot',
  'hours': ('00:00', '24:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 4,
  'coordinate': (13.7323768, 100.532678627535),
  'tags': ['Historical Place',
   'Must See Attraction',
   'Local Culture',
   'Family',
   'Arts'],
  'type': 'tourist spot',
  'hours': ('08:30', '16:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 7,
  'coordinate': (13.74657685, 100.539041420779),
  'tags': ['Shopping',
   'Must See Attraction',
   'Modern',
   'Luxury',
   'Local Culture'],
  'type': 'tourist spot',
  'hours': ('10:00', '22:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 8,
  'coordinate': (13.730728899999999, 100.54150891814254),
  'tags': ['Park', 'Must See Attraction', 'Outdoor', 'Nature', 'Modern'],
  'type': 'tourist spot',
  'hours': ('04:30', '22:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 9,
  'coordinate': (13.74677845, 100.53495402787564),
  'tags': ['Shopping',
   'Must See Attraction',
   'Local Culture',
   'Mall',
   'Nightlife'],
  'type': 'tourist spot',
  'hours': ('10:00', '22:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 11,
  'coordinate': (13.74471505, 100.52991653395821),
  'tags': ['Shopping',
   'Must See Attraction',
   'Luxury',
   'Modern',
   'Local Culture'],
  'type': 'tourist spot',
  'hours': ('10:00', '22:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 12,
  'coordinate': (13.7316989, 100.52937108284219),
  'tags': ['Religion',
   'Modern',
   'Temple',
   'Local Culture',
   'Must See Attraction'],
  'type': 'tourist spot',
  'hours': ('00:00', '24:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 13,
  'coordinate': (nan, nan),
  'tags': ['Historical Place',
   'Park',
   'Outdoor',
   'Nature',
   'Must See Attraction'],
  'type': 'tourist spot',
  'hours': ('05:00', '22:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 14,
  'coordinate': (13.749226799999999, 100.52828110716314),
  'tags': ['Arts', 'Family', 'Historical Place', 'Nightlife', 'Museum'],
  'type': 'tourist spot',
  'hours': ('10:00', '17:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None},
 {'name': 15,
  'coordinate': (13.73294235, 100.53071160312766),
  'tags': ['Modern', 'Local Culture', 'Outdoor', 'Shopping', 'Mall'],
  'type': 'tourist spot',
  'hours': ('10:00', '21:00'),
  'duration': 60,
  'durationH': 1.0,
  'rating': None}]

In [21]:
locData['data']

[(1,
  'Samyan Mitrtown',
  'Historical Place, Mall, Shopping, Must See Attraction, Local Culture',
  13.7344606,
  100.52829290867629,
  None,
  'Bangkok',
  1,
  'MON',
  '00:00',
  '24:00'),
 (4,
  'Queen Saovabha Memorial Institute',
  'Historical Place, Must See Attraction, Local Culture, Family, Arts',
  13.7323768,
  100.532678627535,
  None,
  'Bangkok',
  4,
  'MON',
  '08:30',
  '16:00'),
 (7,
  'CentralWorld',
  'Shopping, Must See Attraction, Modern, Luxury, Local Culture',
  13.74657685,
  100.539041420779,
  None,
  'Bangkok',
  7,
  'MON',
  '10:00',
  '22:00'),
 (8,
  'Lumphini Park',
  'Park, Must See Attraction, Outdoor, Nature, Modern',
  13.730728899999999,
  100.54150891814254,
  None,
  'Bangkok',
  8,
  'MON',
  '04:30',
  '22:00'),
 (9,
  'Siam Paragon',
  'Shopping, Must See Attraction, Local Culture, Mall, Nightlife',
  13.74677845,
  100.53495402787564,
  None,
  'Bangkok',
  9,
  'MON',
  '10:00',
  '22:00'),
 (11,
  'MBK Center',
  'Shopping, Must See Attraction, Luxury, Modern, Local Culture',
  13.74471505,
  100.52991653395821,
  None,
  'Bangkok',
  11,
  'MON',
  '10:00',
  '22:00'),
 (12,
  'Wat Hua Lamphong',
  'Religion, Modern, Temple, Local Culture, Must See Attraction',
  13.7316989,
  100.52937108284219,
  None,
  'Bangkok',
  12,
  'MON',
  '00:00',
  '24:00'),
 (13,
  'Chulalongkorn University Centenary Park',
  'Historical Place, Park, Outdoor, Nature, Must See Attraction',
  None,
  None,
  None,
  'Bangkok',
  13,
  'MON',
  '05:00',
  '22:00'),
 (14,
  'Jim Thompson House',
  'Arts, Family, Historical Place, Nightlife, Museum',
  13.749226799999999,
  100.52828110716314,
  None,
  'Bangkok',
  14,
  'MON',
  '10:00',
  '17:00'),
 (15,
  'Chamchuri Square',
  'Modern, Local Culture, Outdoor, Shopping, Mall',
  13.73294235,
  100.53071160312766,
  None,
  'Bangkok',
  15,
  'MON',
  '10:00',
  '21:00')]

In [15]:
df.head()

,name,lat,long,province,name,open_day,open_time,close_time,tagScore
0,1,13.734461,100.528293,Bangkok,1,MON,00:00,24:00,1
1,4,13.732377,100.532679,Bangkok,4,MON,08:30,16:00,2
2,7,13.746577,100.539041,Bangkok,7,MON,10:00,22:00,1
3,8,13.730729,100.541509,Bangkok,8,MON,04:30,22:00,2
4,9,13.746778,100.534954,Bangkok,9,MON,10:00,22:00,1

In [24]:
df.drop('est_loc_price',axis=1)

,loc_id,loc_name,tag_list,lat,long,province,loc_id,open_day,open_time,close_time,score
0,1,Samyan Mitrtown,"Historical Place, Mall, Shopping, Must See Att...",13.734461,100.528293,Bangkok,1,MON,00:00,24:00,1
1,4,Queen Saovabha Memorial Institute,"Historical Place, Must See Attraction, Local C...",13.732377,100.532679,Bangkok,4,MON,08:30,16:00,2
2,7,CentralWorld,"Shopping, Must See Attraction, Modern, Luxury,...",13.746577,100.539041,Bangkok,7,MON,10:00,22:00,1
3,8,Lumphini Park,"Park, Must See Attraction, Outdoor, Nature, Mo...",13.730729,100.541509,Bangkok,8,MON,04:30,22:00,2
4,9,Siam Paragon,"Shopping, Must See Attraction, Local Culture, ...",13.746778,100.534954,Bangkok,9,MON,10:00,22:00,1
5,11,MBK Center,"Shopping, Must See Attraction, Luxury, Modern,...",13.744715,100.529917,Bangkok,11,MON,10:00,22:00,1
6,12,Wat Hua Lamphong,"Religion, Modern, Temple, Local Culture, Must ...",13.731699,100.529371,Bangkok,12,MON,00:00,24:00,3
7,13,Chulalongkorn University Centenary Park,"Historical Place, Park, Outdoor, Nature, Must ...",NaN,NaN,Bangkok,13,MON,05:00,22:00,2
8,14,Jim Thompson House,"Arts, Family, Historical Place, Nightlife, Museum",13.749227,100.528281,Bangkok,14,MON,10:00,17:00,0
9,15,Chamchuri Square,"Modern, Local Culture, Outdoor, Shopping, Mall",13.732942,100.530712,Bangkok,15,MON,10:00,21:00,0

,loc_id,loc_name,tag_list,lat,long,est_loc_price,province,loc_id,open_day,open_time,close_time,score
0,1,Samyan Mitrtown,"Historical Place, Mall, Shopping, Must See Att...",13.734461,100.528293,None,Bangkok,1,MON,00:00,24:00,1
1,4,Queen Saovabha Memorial Institute,"Historical Place, Must See Attraction, Local C...",13.732377,100.532679,None,Bangkok,4,MON,08:30,16:00,2
2,7,CentralWorld,"Shopping, Must See Attraction, Modern, Luxury,...",13.746577,100.539041,None,Bangkok,7,MON,10:00,22:00,1
3,8,Lumphini Park,"Park, Must See Attraction, Outdoor, Nature, Mo...",13.730729,100.541509,None,Bangkok,8,MON,04:30,22:00,2
4,9,Siam Paragon,"Shopping, Must See Attraction, Local Culture, ...",13.746778,100.534954,None,Bangkok,9,MON,10:00,22:00,1
5,11,MBK Center,"Shopping, Must See Attraction, Luxury, Modern,...",13.744715,100.529917,None,Bangkok,11,MON,10:00,22:00,1
6,12,Wat Hua Lamphong,"Religion, Modern, Temple, Local Culture, Must ...",13.731699,100.529371,None,Bangkok,12,MON,00:00,24:00,3
7,13,Chulalongkorn University Centenary Park,"Historical Place, Park, Outdoor, Nature, Must ...",NaN,NaN,None,Bangkok,13,MON,05:00,22:00,2
8,14,Jim Thompson House,"Arts, Family, Historical Place, Nightlife, Museum",13.749227,100.528281,None,Bangkok,14,MON,10:00,17:00,0
9,15,Chamchuri Square,"Modern, Local Culture, Outdoor, Shopping, Mall",13.732942,100.530712,None,Bangkok,15,MON,10:00,21:00,0

In [7]:
import pandas as pd

db.cursor.execute("SELECT loc_name, lat, long from LOCATION_DATA")

locData = db.cursor.fetchall()

df = pd.DataFrame.from_records(locData, columns= [desc[0] for desc in db.cursor.description])

(Column(name='loc_name', type_code=25), Column(name='lat', type_code=701), Column(name='long', type_code=701))

In [8]:
df.head()

                            loc_name        lat        long
0                    Samyan Mitrtown  13.734461  100.528293
1  Queen Saovabha Memorial Institute  13.732377  100.532679
2                       CentralWorld  13.746577  100.539041
3                      Lumphini Park  13.730729  100.541509
4                       Siam Paragon  13.746778  100.534954

In [9]:
locData

[('Samyan Mitrtown', 13.7344606, 100.52829290867629),
 ('Queen Saovabha Memorial Institute', 13.7323768, 100.532678627535),
 ('CentralWorld', 13.74657685, 100.539041420779),
 ('Lumphini Park', 13.730728899999999, 100.54150891814254),
 ('Siam Paragon', 13.74677845, 100.53495402787564),
 ('MBK Center', 13.74471505, 100.52991653395821),
 ('Wat Hua Lamphong', 13.7316989, 100.52937108284219),
 ('Chulalongkorn University Centenary Park', None, None),
 ('Jim Thompson House', 13.749226799999999, 100.52828110716314),
 ('Chamchuri Square', 13.73294235, 100.53071160312766),
 ('Siam Square', 13.74460455, 100.53310071574116),
 ('Wat Pathum Wanaram', 13.7453177, 100.5365737),
 ('Queen Savang Vadhana Museum', None, None)]

In [10]:
request = {'locations' : [{
				      "id": loc[0],      "coords": {        "lat": loc[1],        "lng": loc[2]      }
			} for loc in locData]
          }

In [11]:
request

{'locations': [{'id': 'Samyan Mitrtown',
   'coords': {'lat': 13.7344606, 'lng': 100.52829290867629}},
  {'id': 'Queen Saovabha Memorial Institute',
   'coords': {'lat': 13.7323768, 'lng': 100.532678627535}},
  {'id': 'CentralWorld',
   'coords': {'lat': 13.74657685, 'lng': 100.539041420779}},
  {'id': 'Lumphini Park',
   'coords': {'lat': 13.730728899999999, 'lng': 100.54150891814254}},
  {'id': 'Siam Paragon',
   'coords': {'lat': 13.74677845, 'lng': 100.53495402787564}},
  {'id': 'MBK Center',
   'coords': {'lat': 13.74471505, 'lng': 100.52991653395821}},
  {'id': 'Wat Hua Lamphong',
   'coords': {'lat': 13.7316989, 'lng': 100.52937108284219}},
  {'id': 'Chulalongkorn University Centenary Park',
   'coords': {'lat': None, 'lng': None}},
  {'id': 'Jim Thompson House',
   'coords': {'lat': 13.749226799999999, 'lng': 100.52828110716314}},
  {'id': 'Chamchuri Square',
   'coords': {'lat': 13.73294235, 'lng': 100.53071160312766}},
  {'id': 'Siam Square',
   'coords': {'lat': 13.74460455, 'lng': 100.53310071574116}},
  {'id': 'Wat Pathum Wanaram',
   'coords': {'lat': 13.7453177, 'lng': 100.5365737}},
  {'id': 'Queen Savang Vadhana Museum', 'coords': {'lat': None, 'lng': None}}]}

In [1]:
import pycurl
import certifi
from io import BytesIO
# Creating a buffer as the cURL is not allocating a buffer for the network response
buffer = BytesIO()
c = pycurl.Curl()
#initializing the request URL
c.setopt(c.URL, 'https://www.scrapingbee.com/')

c.setopt(pycurl.HTTPHEADER, ['header_name1: header_value1',
                                          'header_name2: header_value2'])
#setting options for cURL transfer  
c.setopt(c.WRITEDATA, buffer)
#setting the file name holding the certificates
c.setopt(c.CAINFO, certifi.where())
# perform file transfer
c.perform()
#Ending the session and freeing the resources
c.close()

RuntimeError: asyncio.run() cannot be called from a running event loop

In [1]:
from dbManager import dbManager

db = dbManager()

locations_data = db.get_places_coordinate()

In [3]:
print(locations_data)

None

In [1]:
import pandas as pd

In [20]:
data = [({'coordinate': (0.4385879363140842, 0.6024752310109281),
   'tags': [],
   'type': ['start'],
   'hours': (0, 200),
   'duration': 0,
   'durationH': 0,
   'rating': 0,
   'name': 'start'},
  0),
 ({'name': 'P.15',
   'coordinate': (0.5514462998847065, 0.6172806161569688),
   'tags': ['nature', 'gluten free'],
   'type': ['acomidation'],
   'hours': (8, 14),
   'duration': 37,
   'rating': 4,
   'durationH': 0.6166666666666667},
  8.730492013831354),
 ({'name': 'P.12',
   'coordinate': (0.3570513917530721, 0.39906330465505546),
   'tags': ['gluten free', 'nature'],
   'type': ['tourist spot'],
   'hours': (8, 13),
   'duration': 72,
   'rating': 1,
   'durationH': 1.2},
  10.22273878515078),
 ({'name': 'P.13',
   'coordinate': (0.2813520607716987, 0.48295289778539774),
   'tags': ['outside', 'camping'],
   'type': ['acomidation'],
   'hours': (8, 15),
   'duration': 59,
   'rating': 3,
   'durationH': 0.9833333333333333},
  11.319067041142619),
 ({'name': 'P.9',
   'coordinate': (0.3704878474677993, 0.7111574474058507),
   'tags': ['nature', 'outside'],
   'type': ['food'],
   'hours': (10, 15),
   'duration': 88,
   'rating': 5,
   'durationH': 1.4666666666666666},
  13.030728615791894),
 ({'name': 'P.2',
   'coordinate': (0.47203757680556313, 0.5677718205387596),
   'tags': ['outside', 'beach'],
   'type': ['tourist spot'],
   'hours': (10, 16),
   'duration': 87,
   'rating': 2,
   'durationH': 1.45},
  14.6564323024938),
 ({'name': 'P.1',
   'coordinate': (0.49926744962883474, 0.5513925640578198),
   'tags': ['camping', 'gluten free'],
   'type': ['acomidation'],
   'hours': (10, 16),
   'duration': 33,
   'rating': 0,
   'durationH': 0.55},
  15.238208803510117),
 ({'coordinate': (0.5738028796994746, 0.34718524189709266),
   'tags': [],
   'type': ['end'],
   'hours': (0, 200),
   'duration': 0,
   'durationH': 0,
   'rating': 0,
   'name': 'end'},
  "")]

In [21]:
pdat = [d[0] for d in data]
df = pd.DataFrame.from_dict(pdat)
df['leaveTime'] = [d[1] for d in data]
df = df.rename(columns={"hours":"opening hours"})
df = df.drop(columns=["tags","rating"])
df

,coordinate,type,opening hours,duration,durationH,name,leaveTime
0,"(0.4385879363140842, 0.6024752310109281)",[start],"(0, 200)",0,0.000000,start,0
1,"(0.5514462998847065, 0.6172806161569688)",[acomidation],"(8, 14)",37,0.616667,P.15,8.730492
2,"(0.3570513917530721, 0.39906330465505546)",[tourist spot],"(8, 13)",72,1.200000,P.12,10.222739
3,"(0.2813520607716987, 0.48295289778539774)",[acomidation],"(8, 15)",59,0.983333,P.13,11.319067
4,"(0.3704878474677993, 0.7111574474058507)",[food],"(10, 15)",88,1.466667,P.9,13.030729
5,"(0.47203757680556313, 0.5677718205387596)",[tourist spot],"(10, 16)",87,1.450000,P.2,14.656432
6,"(0.49926744962883474, 0.5513925640578198)",[acomidation],"(10, 16)",33,0.550000,P.1,15.238209
7,"(0.5738028796994746, 0.34718524189709266)",[end],"(0, 200)",0,0.000000,end,

In [24]:
df.to_dict("records")

[{'coordinate': (0.4385879363140842, 0.6024752310109281),
  'type': ['start'],
  'opening hours': (0, 200),
  'duration': 0,
  'durationH': 0.0,
  'name': 'start',
  'leaveTime': 0},
 {'coordinate': (0.5514462998847065, 0.6172806161569688),
  'type': ['acomidation'],
  'opening hours': (8, 14),
  'duration': 37,
  'durationH': 0.6166666666666667,
  'name': 'P.15',
  'leaveTime': 8.730492013831354},
 {'coordinate': (0.3570513917530721, 0.39906330465505546),
  'type': ['tourist spot'],
  'opening hours': (8, 13),
  'duration': 72,
  'durationH': 1.2,
  'name': 'P.12',
  'leaveTime': 10.22273878515078},
 {'coordinate': (0.2813520607716987, 0.48295289778539774),
  'type': ['acomidation'],
  'opening hours': (8, 15),
  'duration': 59,
  'durationH': 0.9833333333333333,
  'name': 'P.13',
  'leaveTime': 11.319067041142619},
 {'coordinate': (0.3704878474677993, 0.7111574474058507),
  'type': ['food'],
  'opening hours': (10, 15),
  'duration': 88,
  'durationH': 1.4666666666666666,
  'name': 'P.9',
  'leaveTime': 13.030728615791894},
 {'coordinate': (0.47203757680556313, 0.5677718205387596),
  'type': ['tourist spot'],
  'opening hours': (10, 16),
  'duration': 87,
  'durationH': 1.45,
  'name': 'P.2',
  'leaveTime': 14.6564323024938},
 {'coordinate': (0.49926744962883474, 0.5513925640578198),
  'type': ['acomidation'],
  'opening hours': (10, 16),
  'duration': 33,
  'durationH': 0.55,
  'name': 'P.1',
  'leaveTime': 15.238208803510117},
 {'coordinate': (0.5738028796994746, 0.34718524189709266),
  'type': ['end'],
  'opening hours': (0, 200),
  'duration': 0,
  'durationH': 0.0,
  'name': 'end',
  'leaveTime': ''}]